//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MFiles.PdfTools {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InternalResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InternalResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MFiles.PdfTools.InternalResources", typeof(InternalResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid certificate authority {0} definition..
        /// </summary>
        internal static string Error_Certificates_InvalidIssuedBy {
            get {
                return ResourceManager.GetString("Error_Certificates_InvalidIssuedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No certificates matching the conditions were found..
        /// </summary>
        internal static string Error_Certificates_NoCertificates {
            get {
                return ResourceManager.GetString("Error_Certificates_NoCertificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No certificates issued by the specified certificate authority were found..
        /// </summary>
        internal static string Error_Certificates_NoCertificatesIssuedBy {
            get {
                return ResourceManager.GetString("Error_Certificates_NoCertificatesIssuedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No certificates matching the specified thumbprint were found..
        /// </summary>
        internal static string Error_Certificates_NoCertificatesThumbprint {
            get {
                return ResourceManager.GetString("Error_Certificates_NoCertificatesThumbprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No certificates with the specified email address were found..
        /// </summary>
        internal static string Error_Certificates_NoCertificatesWithEmailAddress {
            get {
                return ResourceManager.GetString("Error_Certificates_NoCertificatesWithEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No certificates with the specified key usage were found..
        /// </summary>
        internal static string Error_Certificates_NoCertificatesWithKeyUsage {
            get {
                return ResourceManager.GetString("Error_Certificates_NoCertificatesWithKeyUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No certificates with the specified user (certificate subject) were found..
        /// </summary>
        internal static string Error_Certificates_NoCertificatesWithSubject {
            get {
                return ResourceManager.GetString("Error_Certificates_NoCertificatesWithSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No currently valid certificates were found..
        /// </summary>
        internal static string Error_Certificates_NoTimeValidCertificates {
            get {
                return ResourceManager.GetString("Error_Certificates_NoTimeValidCertificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to select only one certificate. A total of {0} certificates were found..
        /// </summary>
        internal static string Error_Certificates_TooManyCertificates {
            get {
                return ResourceManager.GetString("Error_Certificates_TooManyCertificates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registering the required COM compontents failed..
        /// </summary>
        internal static string Error_General_ComComponentRegistrationFailed {
            get {
                return ResourceManager.GetString("Error_General_ComComponentRegistrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The module has not been initialized..
        /// </summary>
        internal static string Error_General_NotInitialized {
            get {
                return ResourceManager.GetString("Error_General_NotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The PDF Tools license was not found or it is invalid..
        /// </summary>
        internal static string Error_InvalidLicense {
            get {
                return ResourceManager.GetString("Error_InvalidLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document has already been signed with the specified certificate..
        /// </summary>
        internal static string Error_PdfTools_DuplicateSignature {
            get {
                return ResourceManager.GetString("Error_PdfTools_DuplicateSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The private key is not available..
        /// </summary>
        internal static string Error_PdfTools_PrivateKeyNotAvailable {
            get {
                return ResourceManager.GetString("Error_PdfTools_PrivateKeyNotAvailable", resourceCulture);
            }
        }
    }
}
