//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MFiles.Internal.Json {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InternalResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InternalResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MFiles.Internal.Json.InternalResources", typeof(InternalResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert the alias candidate &apos;{0}&apos; of the data type &apos;{1}&apos; to an ID..
        /// </summary>
        internal static string Error_UnableToConvertAlias_X_OfType_Y {
            get {
                return ResourceManager.GetString("Error_UnableToConvertAlias_X_OfType_Y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert the data type &apos;{0}&apos; to an ID for the property definition &apos;{1}&apos;..
        /// </summary>
        internal static string Error_UnableToConvertType_X_AndProperty_Y_ToId {
            get {
                return ResourceManager.GetString("Error_UnableToConvertType_X_AndProperty_Y_ToId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate the object type with the alias &apos;{0}&apos;..
        /// </summary>
        internal static string Error_UnableToLocateObjectTypeByAlias_X {
            get {
                return ResourceManager.GetString("Error_UnableToLocateObjectTypeByAlias_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate the property definition with the alias &apos;{0}&apos;..
        /// </summary>
        internal static string Error_UnableToLocatePropertyDefinitionByAlias_X {
            get {
                return ResourceManager.GetString("Error_UnableToLocatePropertyDefinitionByAlias_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate the workflow state with the alias &apos;{0}&apos;..
        /// </summary>
        internal static string Error_UnableToLocateWorkflowStateByAlias_X {
            get {
                return ResourceManager.GetString("Error_UnableToLocateWorkflowStateByAlias_X", resourceCulture);
            }
        }
    }
}
